add path param to all exec statements
Needed to resolve `exec` failures due to `/usr/sbin/lldptool` not being
in the path.

    Error: Parameter onlyif failed on Exec[set-lldp eth0]: 'lldptool get-lldp -i eth0 -g nb adminStatus | grep -qv adminStatus=rxtx' is not qualified and no path was specified. Please qualify the command or specify a path. at /root/puppet-openlldp/spec/fixtures/modules/openlldp/manifests/config/lldp.pp:73
    Wrapped exception:
    'lldptool get-lldp -i eth0 -g nb adminStatus | grep -qv adminStatus=rxtx' is not qualified and no path was specified. Please qualify the command or specify a path.